name: Testing out Github Environment
on: 
  workflow_dispatch: 
env: 
  profession: "Security consultant"
jobs: 
  Script_action: 
    name: Running Github script
    runs-on: ubuntu-latest
    environment: dev

    steps:
     - name: Runs to check environment
       run: echo "my name is ${{ vars.NAME }} and I live in ${{vars.LOCATION}}"

     - name: Trying out Github ENV
       run: | 
         echo "myhair=black" >> "GITHUB_ENV"
 
         
     - name: Trying out Github ENV to show
       run: | 
         echo "I think my hair is $myhair"

     - name: Trying out Github env
       run: | 
         echo "I work as a ${{ env.profession }}"
    
