name: Testing out Github Script
on: 
  workflow_dispatch: 

jobs: 
  Script_action: 
    name: Running Github script
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions/github-script@v2
       with:
         github-token: ${{secrets.GITHUB_TOKEN}}
         script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 You've created this issue comment using GitHub Script!!!"
            })
    
