name: Test out echo 
on: 
  push: 
    branches: [main]
  workflow_dispatch:

jobs: 
  first_job:
    name: Run first job
    runs-on: ubuntu-latest

    steps:
    - name: Run an echo
      run: echo " Hello Nathaneal"

  second_job:
    name: Run second job
    runs-on: ubuntu-latest
    
    steps:
    - name: Run the date function
      run: echo "$(date)"
  
